// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_ExprDirector_Actions
#define _H_ExprDirector_Actions

static const JUtf8Byte* kActionsMenuStr =
"* %i __NewExpression::ExprDirector"
"|* %i __EditConstants::ExprDirector"
"|* %i __Plot2DFunction::ExprDirector"
"|* %i __BaseConversion::ExprDirector %l"
"|* %i __PageSetup::ExprDirector"
"|* %i __PrintTape::ExprDirector %l"
"|* %i __SaveTape::ExprDirector"
"|* %i __ClearTape::ExprDirector %l"
"|* %i __CloseWindow::ExprDirector"
"|* %i __Quit::ExprDirector"
;

enum {
	kNewExprCmd=1,
	kEditConstCmd,
	kNew2DPlotCmd,
	kConvBaseCmd,
	kPageSetupCmd,
	kPrintTapeCmd,
	kSaveTapeCmd,
	kClearTapeCmd,
	kCloseWindowCmd,
	kQuitCmd,
};

#ifndef _H_jx_af_image_jx_jx_file_print
#define _H_jx_af_image_jx_jx_file_print
#include <jx-af/image/jx/jx_file_print.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_file_save
#define _H_jx_af_image_jx_jx_file_save
#include <jx-af/image/jx/jx_file_save.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_edit_clear
#define _H_jx_af_image_jx_jx_edit_clear
#include <jx-af/image/jx/jx_edit_clear.xpm>
#endif

static void ConfigureActionsMenu(JXTextMenu* menu, const int offset = 0) {
	if (menu->IsEmpty() && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#a", JString::kNoCopy));
	}
	menu->SetItemImage(kPrintTapeCmd + offset, jx_file_print);
	menu->SetItemImage(kSaveTapeCmd + offset, jx_file_save);
	menu->SetItemImage(kClearTapeCmd + offset, jx_edit_clear);
};

#endif
