// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_ExprDirector_Preferences_enum
#define _H_ExprDirector_Preferences_enum

enum {
	kToggleKeyPadVisibleCmd=1,
	kEditMacWinPrefsCmd,
	kSaveWindSizeCmd,
};

#endif
