// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_ExprDirector_Preferences
#define _H_ExprDirector_Preferences

static const JUtf8Byte* kPreferencesMenuStr =
"* %b %i __ShowKeypad::ExprDirector"
"|* %i __MacWinXEmulation::ExprDirector %l"
"|* %i __SaveWindowSizeAsDefault::ExprDirector"
;

#include "ExprDirector-Preferences-enum.h"


static void ConfigurePreferencesMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#p");
	}
};

#endif
