// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_Plot2DDirector_Actions_enum
#define _H_Plot2DDirector_Actions_enum

enum {
	kNewExprCmd=1,
	kEditConstCmd,
	kNew2DPlotCmd,
	kConvBaseCmd,
	kPSPageSetupCmd,
	kPrintPSCmd,
	kPrintPlotEPSCmd,
	kPrintMarksEPSCmd,
	kCloseWindowCmd,
	kQuitCmd,
};

#endif
