// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_Plot2DDirector_Actions
#define _H_Plot2DDirector_Actions

static const JUtf8Byte* kActionsMenuStr =
"* %i __NewExpression::Plot2DDirector"
"|* %i __EditConstants::Plot2DDirector"
"|* %i __Plot2DFunction::Plot2DDirector"
"|* %i __BaseConversion::Plot2DDirector %l"
"|* %i __PostScriptPageSetup::Plot2DDirector"
"|* %i __PrintPostScript::Plot2DDirector %l"
"|* %i __PrintPlotAsEPS::Plot2DDirector"
"|* %i __PrintMarksAsEPS::Plot2DDirector %l"
"|* %i __CloseWindow::Plot2DDirector"
"|* %i __Quit::Plot2DDirector"
;

enum {
	kNewExprCmd=1,
	kEditConstCmd,
	kNew2DPlotCmd,
	kConvBaseCmd,
	kPSPageSetupCmd,
	kPrintPSCmd,
	kPrintPlotEPSCmd,
	kPrintMarksEPSCmd,
	kCloseWindowCmd,
	kQuitCmd,
};

#ifndef _H_jx_af_image_jx_jx_file_print
#define _H_jx_af_image_jx_jx_file_print
#include <jx-af/image/jx/jx_file_print.xpm>
#endif

static void ConfigureActionsMenu(JXTextMenu* menu, const int offset = 0) {
	if (menu->IsEmpty() && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#a", JString::kNoCopy));
	}
	menu->SetItemImage(kPrintPSCmd + offset, jx_file_print);
};

#endif
