// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_VarDirector_Actions_enum
#define _H_VarDirector_Actions_enum

enum {
	kNewConstCmd=1,
	kRemoveConstCmd,
	kNewExprCmd,
	kNew2DPlotCmd,
	kConvBaseCmd,
	kCloseWindowCmd,
	kQuitCmd,
};

#endif
