// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_VarDirector_Actions
#define _H_VarDirector_Actions

static const JUtf8Byte* kActionsMenuStr =
"* %i __NewConstant::VarDirector"
"|* %i __RemoveConstant::VarDirector %l"
"|* %i __NewExpression::VarDirector"
"|* %i __Plot2DFunction::VarDirector"
"|* %i __BaseConversion::VarDirector %l"
"|* %i __CloseWindow::VarDirector"
"|* %i __Quit::VarDirector"
;

enum {
	kNewConstCmd=1,
	kRemoveConstCmd,
	kNewExprCmd,
	kNew2DPlotCmd,
	kConvBaseCmd,
	kCloseWindowCmd,
	kQuitCmd,
};


static void ConfigureActionsMenu(JXTextMenu* menu, const int offset = 0) {
	if (menu->IsEmpty() && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#a", JString::kNoCopy));
	}
};

#endif
