#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1

BIN=$PRE/usr/bin
DOC=$PRE/usr/share/doc/leibnitz
APP=$PRE/usr/share/applications
ICON=$PRE/usr/share/pixmaps

if [[ ! -z $PRE ]]; then
	mkdir -p $BIN $APP $ICON;
fi

install -m755 leibnitz $BIN

mkdir -p $DOC
cp README.md COPYING menu_strings $DOC

cp desktop/leibnitz.desktop $APP/
cp desktop/leibnitz.xpm     $ICON/
