#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1;
if [[ -z $PRE ]]; then
	if [[ `uname -o` == Darwin ]]; then
		PRE=`brew --prefix`;
	else
		PRE=/usr/local;
	fi;
fi

BIN=$PRE/bin;
DOC=$PRE/share/doc/leibnitz;
APP=$PRE/share/applications;
ICON=$PRE/share/pixmaps;

mkdir -p $BIN;
install -m755 leibnitz $BIN;

mkdir -p $DOC;
cp README.md COPYING menu_strings $DOC;

if [[ -d desktop ]]; then
	mkdir -p $APP $ICON;
	cp desktop/leibnitz.desktop $APP/;
	cp desktop/leibnitz.png     $ICON/;
fi
