#!/bin/bash

PRE=$1;
if [[ -z $PRE ]]; then
	PRE=/usr;
fi

BIN=$PRE/bin;
DOC=$PRE/share/doc/leibnitz;
APP=$PRE/share/applications;
ICON=$PRE/share/pixmaps;

rm -f  $BIN/leibnitz;
rm -rf $DOC;
rm -f  `find $APP -name 'leibnitz*.desktop'`;
rm -f  `find $ICON -name 'leibnitz*.xpm'`;
