#!/bin/bash

PRE=$1;

BIN=$PRE/usr/bin;
DOC=$PRE/usr/share/doc/leibnitz;
APP=$PRE/usr/share/applications;
ICON=$PRE/usr/share/pixmaps;

rm -f  $BIN/leibnitz;
rm -rf $DOC;
rm -f  `find $APP -name 'leibnitz*.desktop'`;
rm -f  `find $ICON -name 'leibnitz*.png'`;
