#!/bin/bash

PRE=$1;
if [[ -z $PRE ]]; then
	if [[ `uname -o` == Darwin ]]; then
		PRE=`brew --prefix`;
	else
		PRE=/usr/local;
	fi;
fi

BIN=$PRE/bin;
DOC=$PRE/share/doc/leibnitz;
APP=$PRE/share/applications;
ICON=$PRE/share/pixmaps;

rm -f  $BIN/leibnitz;
rm -rf $DOC;
rm -f  `find $APP -name 'leibnitz*.desktop'`;
rm -f  `find $ICON -name 'leibnitz*.png'`;
